name: Python checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run isort
        run: poetry run isort --skip-gitignore --check-only $GITHUB_WORKSPACE
      - name: Run black
        run: poetry run black --check $GITHUB_WORKSPACE
      - name: Run flake8
        run: poetry run flake8 $GITHUB_WORKSPACE
